Week1 homework files for JS BitCamp
bitprj/BitCamp pull request #109
Opened 2021-01-16 02:45 UTC by danzelo1

2021-01-16 07:53 UTC, MinyMeep1 commented on Javascript/homework/responses/1.1-setup.md
> +When your file is all set up, add a title and make your page print "Hello World!"
How do you "Add a title" And make your "page" print "Hello World!"

2021-01-16 08:07 UTC, MinyMeep1 commented on Javascript/homework/responses/1.3-user-input.md
> +Outside of the form, but still in the body, open the `script` tag with the `type` attribute set to `"text/javascript"`.  Inside here, define a function to print the user's selection from the timezone
How do you open the "Script" Tag?

2021-01-16 08:44 UTC, MinyMeep1 commented on Javascript/homework/responses/1.2-buttons.md
> +Radio buttons can be defined using the HTML `input` field if you set the `type` attribute to `"radio"`.  In order to let the computer know that these items are in a group, be sure to give each input
Do I need to search these items up on how to define things using the HTML input?

2021-01-16 08:45 UTC, MinyMeep1 commented on Javascript/homework/responses/1.2-buttons.md
> +Finally, add a break and a `div` tag with a unique `id` right below the submit button.  We will use this later to print the selected timezone.
How do you properly use an id?

2021-01-16 08:50 UTC, MinyMeep1 commented on Javascript/homework/responses/1.5-timezone.md
> +Now, scroll down to the function you wrote to find the selected timezone. Using either conditionals or a switch statement, change the offset based on the timezone selected.  For example, if your comp
What are conditionals or switch statements?

2021-01-18 23:24 UTC, emsesc requested changes
Same issues as Week 4:
1. README.md file format was [updated](https://github.com/bitprj/BitCamp/tree/master/repo_logistics/sample-camp)
2. More bullet points than paragraph formatting would make it more readable
3. Make sure titles (h1/h4 tags) adhere to what is [here](https://github.com/bitprj/BitCamp/tree/master/repo_logistics) (Also add a description for each week's steps!)
4. Fix images by uploading them to a /images directory in /responses `/responses/images`

2021-01-22 01:07 UTC, emsesc approved these changes

2021-01-22 01:07 UTC, emsesc commented on Javascript/homework/responses/1.1-setup.md
> +# Week 1 - Printing the time using JS and HTML
All the response files need a ## header (at the very top) and description. Everything else looks good except for 1.1-setup.md. You may want to reformat the response files differently (remove the week description) since the Learning Lab will end up like this if you title 1.1-setup.md with "Week 1" instead of Task 1.

Week 1 - Printing the time...
Task 2...
Task 3...

Let me know if that makes sense!

2021-01-22 01:07 UTC, emsesc commented on Javascript/README 2.md
> +# Bitcamp JavaScript :rocket:
Why is there a second README file?

2021-01-22 15:05 UTC, merged