Week2 homework files for JS BitCamp
bitprj/BitCamp pull request #110
Opened 2021-01-16 02:47 UTC by danzelo1

2021-01-17 06:53 UTC, MinyMeep1 commented on Javascript/homework/responses/2.1-css-linking.md
> +
I personally see no issue. And if someone doesn't know how to write the code properly maybe we can include it. But it's simply googling how to href a file.

2021-01-17 06:55 UTC, MinyMeep1 commented on Javascript/homework/responses/2.2-body.md
> +In your CSS file, define a body class and set the display to flex.  This will make sure all elements fit the screen appropriately. Next, use the `justify-content`  and `align-items` attributes to cen
How do you define a body class? Should this be googled as well to display to flex?

2021-01-17 06:56 UTC, MinyMeep1 commented on Javascript/homework/responses/2.2-body.md
> +In your CSS file, define a body class and set the display to flex.  This will make sure all elements fit the screen appropriately. Next, use the `justify-content`  and `align-items` attributes to cen
This is all self-explanatory. Unless we need to explain what a `justify-content` is or have them google the exact sheet.

2021-01-17 06:57 UTC, MinyMeep1 commented on Javascript/homework/responses/2.3-clock-design.md
> +After you're satisfied with the body of your page, define a block that styles elements in the `clock` class.
How do you "define a block that styles elements in the `clock` class." unclear.

2021-01-17 07:06 UTC, MinyMeep1 commented on Javascript/homework/responses/2.3-clock-design.md
> +Once again, you'll want to set your `display` to `flex` and center your text using `align-items` and `justify-content` .  You need to do this again because these attributes in the body only centered
What is the display or flex? The question stands should we have students google this or explain every detail.

2021-01-17 07:07 UTC, MinyMeep1 commented on Javascript/homework/responses/2.3-clock-design.md
> +Lastly is the color.  I used the `rgba()` tool to define my color.  The first 3 numbers represent the amount of red, green, and blue in the color, respectively. The fourth number is the opacity on a
What is the rgba tool and how do we use this?

2021-01-17 07:09 UTC, MinyMeep1 commented on Javascript/homework/responses/2.3-clock-design.md
> +Lastly is the color.  I used the `rgba()` tool to define my color.  The first 3 numbers represent the amount of red, green, and blue in the color, respectively. The fourth number is the opacity on a
"The first 3 numbers represent the amount of red, green, and blue in the color, respectively." This explains it but not fully or how to open it.

2021-01-17 07:12 UTC, MinyMeep1 commented on Javascript/homework/responses/2.4-form-layout.md
> +Lastly, you'll define a timezone class to style the labels and buttons used for your timezone selector.  Similarly to the way you defined the clock styles using the unique id from the clock div, prec
Pretty good with this.

2021-01-18 23:24 UTC, emsesc requested changes
Same issues as Week 4:
1. README.md file format was [updated](https://github.com/bitprj/BitCamp/tree/master/repo_logistics/sample-camp)
2. More bullet points than paragraph formatting would make it more readable
3. Make sure titles (h1/h4 tags) adhere to what is [here](https://github.com/bitprj/BitCamp/tree/master/repo_logistics) (Also add a description for each week's steps!)
4. Fix images by uploading them to a /images directory in /responses `/responses/images`

2021-01-22 01:06 UTC, emsesc approved these changes

2021-01-22 15:10 UTC, emsesc commented
@danzelo1 Please add a italicized quick description of the course in `course-deatils.md` under the title. Refer to [this](https://github.com/emsesc/sample-learninglab/blob/main/course-details.md) for an example. Also, go ahead and resolve the conflicts. Thanks!

2021-01-22 22:47 UTC, closed without merging