Week3 js homework
bitprj/BitCamp pull request #111
Opened 2021-01-17 08:08 UTC by danzelo1

2021-01-17 20:07 UTC, MinyMeep1 commented on Javascript/homework/responses/3.3-clock-digits.md
> +You'll notice that the numbers overlap in one spot and you can't read them.  In the next step we'll use rotation tools to change the positioning of each digit on the clock.
No issues with this section.

2021-01-17 20:14 UTC, MinyMeep1 commented on Javascript/homework/responses/3.4-rotation.md
> +*Don't forget to delete the border from `.clock .number` after this step if you included it earlier.*
No issues with 3.4

2021-01-17 20:31 UTC, MinyMeep1 commented on Javascript/homework/responses/3.5-clock-hands.md
> +Inside of your clock div define three divs - these will represent the hands on our clock.  For each div, set the class to "hand [type of hand]" and set the data-* attribute to `data-[type of hand]-ha
"Inside of your clock div define three divs" I didn't quite understand this line.

2021-01-18 23:22 UTC, emsesc requested changes
Same issues as Week 4:
1. README.md file format was [updated](https://github.com/bitprj/BitCamp/tree/master/repo_logistics/sample-camp)
2. More bullet points than paragraph formatting would make it more readable
3. Make sure titles (h1/h4 tags) adhere to what is [here](https://github.com/bitprj/BitCamp/tree/master/repo_logistics)
4. Fix images by uploading them to a /images directory in /responses `/responses/images`

2021-01-22 00:58 UTC, emsesc approved these changes

2021-01-22 15:10 UTC, emsesc commented
@danzelo1 Resolve conflicts, but everything else is good

2021-01-22 23:01 UTC, merged