Week4 js homework
bitprj/BitCamp pull request #112
Opened 2021-01-18 04:06 UTC by danzelo1

2021-01-18 06:13 UTC, MinyMeep1 commented on Javascript/homework/responses/4.1-page-setup.md
> +Now, add a block in your css file that selects the `"digital"` class like so:
What's a block. And will this be on the sheet sheet.

2021-01-18 23:14 UTC, emsesc requested changes
Make sure to change the week titles to those requested here: https://github.com/bitprj/BitCamp/tree/master/repo_logistics (Under The Github Action)

A bit more formatting (more bullet points than paragraphs) would also be great! Otherwise, the content is good.,

2021-01-18 23:14 UTC, emsesc commented on Javascript/README.md
> +
We actually recently updated the README.md format. It's pretty similar, but you will just have to move some stuff around: https://github.com/bitprj/BitCamp/tree/master/repo_logistics/sample-camp

2021-01-18 23:14 UTC, emsesc commented on Javascript/homework/responses/4.1-page-setup.md
> +### Week 4 - Toggling between digital and analog clocks and incoporating advanced features
Make sure all the response files are formatted like described under "The Github Action" https://github.com/bitprj/BitCamp/tree/master/repo_logistics

2021-01-18 23:14 UTC, emsesc commented on Javascript/homework/responses/4.2-more-buttons.md
> +![Screen Shot 2021-01-17 at 9.31.52 PM](/Users/danielleanzelone/Library/Application Support/typora-user-images/Screen Shot 2021-01-17 at 9.31.52 PM.png)
Might want to fix the images. If you're using a local markdown editor, you'll need to upload the image to Github.

2021-01-22 00:57 UTC, emsesc approved these changes

2021-01-22 15:11 UTC, emsesc commented
@danzelo1 Resolve conflicts, but everything else looks great!

2021-01-22 23:03 UTC, merged