Added week 1 and 2 files
bitprj/BitCamp pull request #53
Opened 2021-01-03 16:53 UTC by MurraySmith27

Added the files for week 1 and week 2 live streams and homework.

2021-01-03 18:37 UTC, Bahburs requested changes
For `week1/livestream/script.md`, I would format it how you did it for Week 2 in more of a bulleted list format. It is just easier to read and looks much better!

2021-01-03 18:38 UTC, Bahburs reviewed
Other than a few styling changes (with markdown), the content itself looks great.

2021-01-03 18:50 UTC, emsesc requested changes
Overall, great content! I would just change the formatting with markdown to make it more readable. I would also recommend transferring the content in the solutions pdfs into a markdown file. That way, in case changes need to be made, they can be committed in Github.

2021-01-03 18:50 UTC, emsesc commented on GameDev/week1/livestream/script.md
> -Put your script here.
Agree with @Bahburs -- some styling with markdown will improve readability

2021-01-03 18:50 UTC, emsesc commented on GameDev/week2/homework/issues/Week 2 Homework Instructions.md
> +
same issue with styling (this is better than the live stream script formatting though)
example: https://github.com/TheDirector23/azure-functions-course/blob/main/responses/2.0-postman.md
markdown cheatsheet: https://www.markdownguide.org/cheat-sheet/

2021-01-03 19:06 UTC, MurraySmith27 commented
Okay I made some formatting changes. Thanks for the feedback!

2021-01-04 00:39 UTC, lazyplatypus commented
@emsesc make sure to attach the issue here :)

2021-01-04 01:14 UTC, emsesc commented
@MurraySmith27 Looks much better!

2021-01-04 01:27 UTC, merged