Add outline markdowns
bitprj/BitCamp pull request #54
Opened 2021-01-04 00:37 UTC by chris8736

Added week outlines and homework solutions without pictures / explanations (which I have in a separate doc for now).

2021-01-04 02:08 UTC, lazyplatypus commented
Hey @chris8736, all prs need to be associated with an issue. can you mention in your PR description what issue this would be closing?

2021-01-04 09:09 UTC, chris8736 commented
Got it, edited.

2021-01-09 15:23 UTC, emsesc requested changes
Overall, great organization and content! My only comment is to add more formatting so it's easier to read. I added comments throughout to suggest some edits.

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/homework/issues/audioHomework.md
> +For further mastery of audio:
I like the bulleted formatting! However, you have to put a space between "-" and your content in order for it to show as bullet points. Try using the preview button shown below to preview what your file looks like in rich format!

![image](https://user-images.githubusercontent.com/69332964/104095257-e577b680-5263-11eb-8194-7ba973a0703d.png)

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/homework/issues/audioHomework.md
> +Now, what I’d like for you to do this week is to find some sound assets of your own, either using the websites I’ve shown you, some other source, or even your own recording. Even though we’re not wor
Can you make this more concise by making it a bulleted todo list?

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/livestream/outline.md
> +
Same issue here with the bullet points. Use the "preview" option to see how the markdown works, and [here's](https://www.markdownguide.org/cheat-sheet/) a cheatsheet on how to use markdown! (it's kind of like a formatting coding language)

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/livestream/outline.md
> +Outline:
Make "Outline:" a title (refer to https://www.markdownguide.org/cheat-sheet/)

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/livestream/outline.md
> +Component Referencing (5 mins)
These section headers would benefit from being bolded or changed to a header https://www.markdownguide.org/cheat-sheet/

2021-01-09 15:23 UTC, emsesc commented on GameDev/week6/livestream/script.md
Refer to my previous comments about formatting :)

2021-01-09 15:23 UTC, emsesc commented on GameDev/week7/livestream/script.md
> +Particle System basics (10 mins)
Awesome content, but can you make it more readable? I know it's a script though, so that may be more challenging. Maybe split it into sections?

2021-01-14 23:09 UTC, emsesc approved these changes
@chris8736 the formatting looks awesome! Looks good 👍

2021-01-14 23:09 UTC, merged