Week 3 Content
bitprj/BitCamp pull request #95
Opened 2021-01-11 02:30 UTC by ColeHorvat

Sorry just realized I think I pulled to the wrong repo. Here's the week 3 content.

2021-01-11 16:23 UTC, emsesc requested changes
Overall, great formatting of the written portion and it's easy to read (which is good). Only comment is that the code could be formatted with syntax highlighting. Refer to the comments :)

2021-01-11 16:23 UTC, emsesc commented on GameDev/week3/homework/issues/starter.md
> +	using System.Collections;
Use the file extension of ".cs" for this file since it's all code

2021-01-11 16:23 UTC, emsesc commented on GameDev/week3/homework/solution/solutions.md
> +
You can format your code like this with syntax highlighting:
```cs
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
```
to do this, place ` ```cs` on a line, your code below that, and finally ` ``` ` to close off the code.

2021-01-11 16:23 UTC, emsesc commented on GameDev/week3/livestream/script.md
> +- *Introduce yourselves*
Awesome formatting for the text, but same issue with code formatting here. Add syntax highlighting: https://www.markdownguide.org/extended-syntax/#syntax-highlighting

2021-01-11 17:35 UTC, ColeHorvat commented
> Overall, great formatting of the written portion and it's easy to read (which is good). Only comment is that the code could be formatted with syntax highlighting. Refer to the comments :)

Syntax colouring has been added

2021-01-14 21:43 UTC, emsesc approved these changes
Looks good!

2021-01-14 21:43 UTC, merged